#!/bin/bash
#
# prerm-derp
#
# prepm for derp
#
# Author: fattire

set -e

clear_mime()
{
xdg-icon-resource uninstall --size 256 application-derp
xdg-mime uninstall /usr/share/derp/derp-derp.xml
}

case "$1" in
   remove|upgrade)
   if dpkg-query -W xdg-utils; 
       then clear_mime;
   fi
   rm -f /usr/share/derp/src/*.pyc
   ;;

   *)

   ;;
esac

exit 0

